name: 
 
on:
  pull_request:
    paths:
        - 'Chapter01/**'
 
jobs:
  Chapter01:
    runs-on: ubuntu-latest
    steps:
      - name: install build essentials
        run:
          sudo apt update &&
          sudo apt install gcc g++ libgtest-dev cmake make build-essential sed gcc-aarch64-linux-gnu g++-aarch64-linux-gnu  qemu-user
      
      - uses: actions/checkout@v3

      - name: clang format
        run: find Chapter01 -regex ".*\\.\\(cpp\\|hpp\\|c\\|h\\)" | xargs clang-format -style=file --Werror --dry-run

      - name: test
        run: |
          cd Chapter01 && mkdir build && cd build && cmake .. -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ && make -j8 && cd .. && qemu-aarch64 -L /usr/aarch64-linux-gnu ./build/WasmParser
