name: 
 
on:
  pull_request:
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: install build essentials
        run:
          sudo apt update &&
          sudo apt install gcc g++ libgtest-dev cmake make build-essential sed gcc-aarch64-linux-gnu g++-aarch64-linux-gnu  
      
      - name: install qemu
        run:
          sudo apt install qemu-user
        
      - uses: actions/checkout@v3

      - name: clang format
        run: find Chapter01 -regex ".*\\.\\(cpp\\|hpp\\|c\\|h\\)" | xargs clang-format -style=file --Werror --dry-run

      - name: test
        run: |
          cd Chapter01 && mkdir build && cd build && cmake .. && make -j8 && cd .. && qemu-aarch64 -L /usr/aarch64-linux-gnu ./build/WasmParser
